### PR TITLE
Replace syndication targets with the response from the endpoint

### PR DESCRIPTION
**Pull request by pstuifzand**
I put back the original fetchSyndicationTargets function. The response doesn't contain "ok", as the micropub helper returns the json object.

### CODE REVIEW

**Comment by keithjgrant** [comment]
Does the micropub helper always return an array? Or should we still typecheck that and store an empty array otherwise?

**Comment by pstuifzand** [comment]
https://github.com/grantcodes/micropub/blob/master/src/main.js#L505

It returns the json object itself when it is ok. It will call reject on error.

**Comment by pstuifzand** [comment]
That would mean that only the "response.ok" part should be removed from the if.

**Comment by keithjgrant** [comment]
Yeah, looks like. If you want to do that, I'll merge in the change.

**Comment by pstuifzand** [comment]
I tested it: Omnibear loads the syndication endpoints https://p83.nl/p/655

**Comment by keithjgrant** [comment]
Thanks!

**Pull request merged**
