### PR TITLE
Increase version of micropub-helper to 1.3.10

### PR DESCRIPTION
**Pull request by pstuifzand**
- This fixes encoding of array arguments for categories and mp-syndicate-to. https://github.com/grantcodes/micropub/issues/8
- It also contains Link rel parsing it seems. https://github.com/grantcodes/micropub/issues/7

### CODE REVIEW

**Comment by pstuifzand** [comment]
I already build a version with these new features and posted something to Twitter using syndication.
https://publog.stuifzandapp.com/posts/185
https://twitter.com/pstuifzand/status/963863244850040832

**Comment by keithjgrant** [comment]
Thanks!

**Comment by pstuifzand** [comment]
@keithjgrant could you please update the version of the extension so it includes this micropub helper upgrade?

**Comment by keithjgrant** [comment]
v1.0.1 is being pushed out now in Chrome + Firefox stores. This will take anywhere from a few minutes to a few hours, typically.

**Pull request merged**
